name = "VectorizedArgMinMax"
uuid = "9f678474-6fb6-41cc-a5e6-6151c34b4bd5"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com>"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
LoopVectorization = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
